
* file examples/freemem.s

* a sample Intuition program to display a window constantly showing
* the free memory figure, until it's closed

* this source code (C) HiSoft 1987 All Rights Reserved

* both source and binary are FreeWare and may be distributed free of charge
* so long as copyright messages are not removed

* revision history:
* 7th June 86	written
* 22nd Sept 86	changed includes

* ensure case dependent and debug
	opt	c+,d+

* firstly get the required constants and macr