*HELP*
*INVENTORY* AND* EXITS*
*DOWN*
*TAKE* EVERYTHING* AND* EXAMINE* EVERYTHING*
*SOUTH*
*UP.*SOUTH*****
*W*****
*W*****
*W*****
*OOPS*****
*W*****
*TAKE* POPPY* SEED* POD* AND* EXAMINE* IT*
*LISTEN*
*E*.E*.E*.N*.N* (Multi-tasking means no need to wait for pictures to draw.)
*OOPS*****
*Wave* poppy* pod*
*n*
*n*****
*oops*****
*n* take* the* mirror* throw* everything* but* the* mirror* at* the* tree*
*s* s* e*
*n* n**********
*u******
*take* the* berry* and* examine* it* and* drop* it*
*d.*n*
*DROP* ALL*
*wear* all* but* the* berry* and* mirror*
*take* all*
*s*
*s**********
*e**********
*s**********
*take* all*
*words******
n*****
w*.w*.n*.n*.throw* coins*,mirror*,dice* and* berry*
*pictures********
*n*******
*QUIT*
*YES*
