/*
 *   The include file to include all the other include files - (FOLLOW THAT !)
 *
 *   Copyright c 1987 By Level 9 Computing & Leon Thrane.  All Rights Reserved.
 *   9 Mendip Road, Crown Wood, Bracknell, Berkshire, RG12 3XG - (0344) 487597
 *
 *   Author: Leon Thrane (July 1987)
 */

/*
 *   Standard C include files
 */

#include  <stdlib.h>
#include  <stdio.h>

/*
 *   Amiga specific include files
 */

#include  <exec/types.h>
#include  <exec/memory.h>
#include  <graphics/view.h>

/*
 *   Custom library 'Grafix.lib' include file
 */

#include  "grafix.h"

/*
 *   H.E.R.O. specific include files
 */

#include "structs.h"
