**1
*****examine everyone
*******follow detective
*****examine matchbox
*******stop following
**look in vault
***examine bags
***run to my grave
*****get pebble
***go north
*****get thistledown
***run to shed
*****enter shed
*****wait
*******run to leaf and take it
*******run to my grave
*****get pebble
*****wait for joe
*******examine figure
*****follow joe
*****wait
*******stop following
**examine bert and edna
*****southwest
*****examine stonework
***examine plinth
***wake statue
*****alex, follow me
***run to joe
*****examine the sarcophagus
***push the urn
****RESTART
***Y
