צצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצצ had been all sorts of trouble"] 
; 
[2493:knighted Lancelot, and bade him stay and dine with them. 
As they sat at table and the drinks flowed, Lancelot stole many 
a glance at Queen Guenever. Truly, he thought, she was a most 
beautiful and stately woman. And as the evening wore on, it came 
to him that he was fast losing his heart to her. 
%At times, their eyes met and Guenever did look away coyly, 
like a maiden. At length, with his heart in his mouth, he 
essayed to beg of her the favour of be"¼~*—ךHשQצל	צ7Ú¯:Düˆ?ָ$¥שפ™ך_cÿ)’?”ֹףָ?־d‰׳rüdOÊ„¯¨ƒנü±‎`|‰ץע ‏²
dÝH‎װ‰קR2üÿF'˜OÜֲpNa>Eדה—ÊטֿוtfAü®ופ4ß`?°צ£$~ְ4hi¾ִNdÞדןY&O½d™½d÷ß¾“$|ׁש%ע dÊ†‘„l‏i2נ¡%?ָHu$ׂJ_‘#PM$¿)³^?)ֶ‚nhC׀¡;B¦„	:´"טRאÙ$26rü׀Úפ'טN׀©¡KB~„־	ֽ©# Mo¿·Ý¡¼¢9}₪4!÷-Dצ״_טֵt}9€ִ—4!÷‹ך,lˆ¿¶dÛ8דןY?סד<#ץI’$ֹ4ׂש%ֽn°"5ד‚u¯—ה´>^ֶהא¢(ƒר”²KגT¾Y‎ ‏ÿָ‏ Aü
CMע=7ז†‏¨%ה