**e
****e
**look at rainbow
**e
**w
*w
*n
****n
***nw. n
**examine brambles
**examine hair
**find yak
**go to shop
**knock on door
**examine knocker
**follow centaur
**examine centaur
**get envelope and shovel and leave
**open envelope and read the letter
**go to cottage
****run to llama
****get flower, run to forest, wait for nymph and give flower to nymph
**gnymph, get a grip on yourself, woman
**gnymph, go to rainbow
**follow gnymph
**gnymph, get shovel, e, dig
**stop following
**wait 5, e
**examine ingrid
****restart**
*yes
