/**
*
*  This header defines system portable typedefs
*
**/
typedef char           BYTE;     /* signed 8 bit integer */
typedef unsigned char  UBYTE;    /* unsigned 8 bit int   */
typedef short          WORD;     /* signed 16 bit int    */
typedef unsigned short UWORD;    /* unsigned 16 bit int  */
typedef unsigned short USHORT;   /* unsigned 16 bit int  */
typedef long           LONG;     /* signed 32 bit int    */
typedef unsigned long  ULONG;    /* unsigned 32 bit int  */

#define TRUE   1
#define FALSE  0
