cd \ghost.l9\part1.l9
arc a main.arc main.l9\*.*
arc a d:\ghost.l9\part1.l9\part1.arc *.*
cd \ghost.l9\part2.l9
arc a main.arc main.l9\*.*
arc a d:\ghost.l9\part2.l9\part2.arc *.*
cd \ghost.l9\part3.l9
arc a main.arc main.l9\*.*
arc a d:\ghost.l9\part3.l9\part3.arc *.*
cd \ghost.l9
arc a d:\ghost.l9\ghost.arc *.*
arc a d:\ghost.l9\auto\auto.arc auto\*.*
arc a d:\ghost.l9\ghost.l9\ghostpic.arc ghost.l9\*.*